# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: showtime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshowtime.proto\",\n\x0cScheduleData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"0\n\x0cJsonSchedule\x12 \n\tschedules\x18\x01 \x03(\x0b\x32\r.ScheduleData\"\x19\n\x08Schedule\x12\r\n\x05movie\x18\x01 \x01(\t\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\x08\n\x06\x45mpty22\x8f\x01\n\x08Showtime\x12#\n\x07GetJson\x12\x07.Empty2\x1a\r.JsonSchedule\"\x00\x12+\n\x13GetSchedulesPerDate\x12\x05.Date\x1a\t.Schedule\"\x00\x30\x01\x12\x31\n\x17GetSchedulesPerDateJson\x12\x05.Date\x1a\r.ScheduleData\"\x00\x62\x06proto3')



_SCHEDULEDATA = DESCRIPTOR.message_types_by_name['ScheduleData']
_JSONSCHEDULE = DESCRIPTOR.message_types_by_name['JsonSchedule']
_SCHEDULE = DESCRIPTOR.message_types_by_name['Schedule']
_DATE = DESCRIPTOR.message_types_by_name['Date']
_EMPTY2 = DESCRIPTOR.message_types_by_name['Empty2']
ScheduleData = _reflection.GeneratedProtocolMessageType('ScheduleData', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULEDATA,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:ScheduleData)
  })
_sym_db.RegisterMessage(ScheduleData)

JsonSchedule = _reflection.GeneratedProtocolMessageType('JsonSchedule', (_message.Message,), {
  'DESCRIPTOR' : _JSONSCHEDULE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:JsonSchedule)
  })
_sym_db.RegisterMessage(JsonSchedule)

Schedule = _reflection.GeneratedProtocolMessageType('Schedule', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Schedule)
  })
_sym_db.RegisterMessage(Schedule)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Date)
  })
_sym_db.RegisterMessage(Date)

Empty2 = _reflection.GeneratedProtocolMessageType('Empty2', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY2,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Empty2)
  })
_sym_db.RegisterMessage(Empty2)

_SHOWTIME = DESCRIPTOR.services_by_name['Showtime']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCHEDULEDATA._serialized_start=18
  _SCHEDULEDATA._serialized_end=62
  _JSONSCHEDULE._serialized_start=64
  _JSONSCHEDULE._serialized_end=112
  _SCHEDULE._serialized_start=114
  _SCHEDULE._serialized_end=139
  _DATE._serialized_start=141
  _DATE._serialized_end=161
  _EMPTY2._serialized_start=163
  _EMPTY2._serialized_end=171
  _SHOWTIME._serialized_start=174
  _SHOWTIME._serialized_end=317
# @@protoc_insertion_point(module_scope)
