# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import showtime_pb2 as showtime__pb2


class ShowtimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJson = channel.unary_unary(
                '/Showtime/GetJson',
                request_serializer=showtime__pb2.Empty2.SerializeToString,
                response_deserializer=showtime__pb2.JsonSchedule.FromString,
                )
        self.GetSchedulesPerDate = channel.unary_stream(
                '/Showtime/GetSchedulesPerDate',
                request_serializer=showtime__pb2.Date.SerializeToString,
                response_deserializer=showtime__pb2.Schedule.FromString,
                )
        self.GetSchedulesPerDateJson = channel.unary_unary(
                '/Showtime/GetSchedulesPerDateJson',
                request_serializer=showtime__pb2.Date.SerializeToString,
                response_deserializer=showtime__pb2.ScheduleData.FromString,
                )


class ShowtimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetJson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchedulesPerDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchedulesPerDateJson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShowtimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJson': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJson,
                    request_deserializer=showtime__pb2.Empty2.FromString,
                    response_serializer=showtime__pb2.JsonSchedule.SerializeToString,
            ),
            'GetSchedulesPerDate': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSchedulesPerDate,
                    request_deserializer=showtime__pb2.Date.FromString,
                    response_serializer=showtime__pb2.Schedule.SerializeToString,
            ),
            'GetSchedulesPerDateJson': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchedulesPerDateJson,
                    request_deserializer=showtime__pb2.Date.FromString,
                    response_serializer=showtime__pb2.ScheduleData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Showtime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Showtime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Showtime/GetJson',
            showtime__pb2.Empty2.SerializeToString,
            showtime__pb2.JsonSchedule.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSchedulesPerDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Showtime/GetSchedulesPerDate',
            showtime__pb2.Date.SerializeToString,
            showtime__pb2.Schedule.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSchedulesPerDateJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Showtime/GetSchedulesPerDateJson',
            showtime__pb2.Date.SerializeToString,
            showtime__pb2.ScheduleData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
